name: relpose_gnn
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch==1.8.2
  - torchvision==0.9.1
  - cudatoolkit==11.1.1
  - intel-openmp
  - mkl
  - mkl_fft
  - mkl_random
  - ninja
  - numpy
  - pillow
  - pip
  - scipy
  - setuptools
  - transforms3d
  - wheel
  - pytest
  - pyyaml
  - pip:
      - -r requirements-cu111.txt